name: Update 6-digit Code and Post to Discord

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 6-digit Code
        run: echo $((RANDOM % 900000 + 100000)) > code.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add code.txt
          git commit -m "Updated 6-digit code"
          git push

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          CODE=$(cat code.txt)
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🔢 New Code: **$CODE** (Valid for 20 mins)\"}" \
               "$DISCORD_WEBHOOK"
